version: '3'

services:
  wanderlink.org:
    build:
    volumes:
      - .:/usr/src/wanderlink.org
      - /usr/src/wanderlink.org/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
